const portfolioData = [
  {
    id: 57,
    title: "万灵起源",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/wlqy-01.mp4",
    posterUrl: "./files/portfolio-bc/wlqy-01-poster.webp", 
    fullDescription:
      "少女戰鬥RPG，投放韩国，主要是玩法展示",
    tags: ["韩国", "游戏", "RPG"],
  },
  {
    id: 58,
    title: "万灵起源",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/wlqy-02.mp4",
    posterUrl: "./files/portfolio-bc/wlqy-02-poster.webp", 
    fullDescription:
      "少女戰鬥RPG，投放韩国，主要是玩法展示",
    tags: ["韩国", "游戏", "RPG"],
  },
  {
    id: 67,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-01.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 68,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-02.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 69,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-03.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 70,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-04.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 71,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-05.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 72,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-06.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 73,
    title: "猫之城",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/mzc-banner-07.webp",
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 74,
    title: "猫之城",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/mzc-01.mp4",
    posterUrl: "./files/portfolio-bc/mzc-01-poster.webp", 
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 75,
    title: "猫之城",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/mzc-02.mp4",
    posterUrl: "./files/portfolio-bc/mzc-02-poster.webp", 
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 76,
    title: "猫之城",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/mzc-03.mp4",
    posterUrl: "./files/portfolio-bc/mzc-03-poster.webp", 
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 77,
    title: "猫之城",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/mzc-04.mp4",
    posterUrl: "./files/portfolio-bc/mzc-04-poster.webp", 
    fullDescription:
      "策略RPG，投放韩国，多以角色展示为主",
    tags: ["RPG", "游戏", "韩国"],
  },
  {
    id: 78,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-01.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 79,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-02.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 80,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-03.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 81,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-04.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 82,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-05.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 83,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-06.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 84,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-07.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 85,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-08.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 86,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-09.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 87,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-10.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 88,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-11.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 89,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-12.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 90,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-13.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 91,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-14.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 92,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-15.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 93,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-16.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 94,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-17.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 95,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-18.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 96,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-19.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 97,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-20.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 98,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-21.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 99,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-22.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 100,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-23.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 101,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-24.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 102,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-25.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 103,
    title: "休闲游戏",
    description: "",
    mediaType: "image",
    mediaUrl: "./files/portfolio-bc/bc-banner-26.webp",
    fullDescription:
      "",
    tags: ["休闲", "游戏",],
  },
  {
    id: 104,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-01.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-01-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 105,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-02.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-02-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 106,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-03.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-03-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 107,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-04.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-04-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 108,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-05.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-05-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 109,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-06.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-06-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 110,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-07.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-07-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 111,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-08.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-08-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 112,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-09.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-09-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 113,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-10.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-10-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 114,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-11.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-11-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 115,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-12.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-12-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 116,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-13.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-13-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 117,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-14.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-14-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 118,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-15.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-15-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 119,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-16.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-16-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 120,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-17.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-17-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 121,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-18.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-18-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 122,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-19.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-19-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 123,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-20.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-20-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },
  {
    id: 124,
    title: "休闲游戏",
    description: "",
    mediaType: "video",
    mediaUrl: "./files/portfolio-bc/bc-video-21.mp4",
    posterUrl: "./files/portfolio-bc/bc-video-21-poster.webp", 
    fullDescription:
      "",
    tags: ["休闲", "游戏"],
  },

];
